#!/bin/bash

# deed: managing your todo in todo.txt format
# author: @ne1nene (Soulmine)
# TODO add verbose msg
# TODO add readme.md

print_help () {
    echo "deed: managing your todo in todo.txt format"
    echo "usage: deed [OPTION] [ACTION] [TARGET_INDEX] [-t] [TARGET_FILE]"
    echo "example:"
    echo "  \`deed\`"
    echo "  \`deed do the dishes\`"
    echo "  \`deed -a \"do the dishes\"\`"
    echo ""
    echo "variable:"
    echo "  \$TODO_DIR                             directory where all file related to your todo (todo, done, report,"
    echo "                                        someday, backlog) will reside"
    echo ""
    echo "option:"
    echo "  -l, --list LIST_FILE                   when on, will list DONE_FILE together with TODO_FILE. if LIST_FILE"
    echo "                                         is given and is a file in TODO_DIR, deed will only list tasks in LIST_FILE"
    echo "  -v, --verbose                          when on, deed will print more log stdout"
    echo "  -h, --help                             print this message and exit the script"
    echo ""
    echo "action:"
    echo "  -o, --open                             open TARGET_FILE in your editor"
    echo "  -a, --add TASK                         add a TASK to TARGET_FILE"
    echo "  -d, --done INDEX                       mark TASK with INDEX index a done in TARGET_FILE"
    echo "  -c, --clean                            move all done tasks to DONE_FILE"
    echo "  -p, --prior PRIOR                      mark TASK with INDEX index with priority of PRIOR"
    echo "  -t, --target TARGET_FILE               change TARGET_FILE (default is TODO_FILE)"
    echo "  -r, --report                           log a report of complete and incomplete task in TODO_FILE and DONE_FILE to REPORT_FILE"
    echo "  -f, --filter REGEX                     only print out task that match the given regex REGEX in TARGET_FILE"
    echo "  -n, --now                              filter task in TARGET_FILE with predefined REGEX inside the script"
    echo "  -del, --delete INDEX                   delete task with INDEX index in TARGET_FILE"
    echo "  -app, --append INDEX TEXT              append TEXT to task with INDEX index in the TARGET_FILE "
    echo "  -mov, --move INDEX DESTI_TARGET_FILE   move task with INDEX index from TARGET_FILE to DESTI_TARGET_FILE"
    echo ""
}

check_dir_usuable() {
    if [ ! -d "$1" ]; then
        echo "deed: directory $1 does not exist"
        mkdir "$1"
        echo "deed: directory $1 has been created"
    fi
}

check_file_usuable() {
    if [ ! -e "$1" ]; then
        echo "deed: file $1 does not exist."
        touch "$1"
        echo "deed: file $1 has been created"
    elif [ ! -f "$1" ]; then
        echo "error: file $1 exists but is not a regular file."
        exit 1
    elif [ ! -r "$1" ]; then 
        echo "error: file $1 exists but is not readable."
        exit 1
    elif [ ! -w "$1" ]; then 
        echo "error: file exists but is not writable."
        exit 1
    fi
}

EDITOR=${EDITOR:-notepad} # nvim, nano, notepad etc.

# where all todo.txt file will be stored
TODO_DIR="${TODO_DIR:-$HOME}"
# defined todo.txt file
TODO_FILE="${TODO_DIR}/todo.txt"
# other optional file, derived TODO_FILE's file extension
DONE_FILE="${TODO_DIR}/done.${TODO_FILE##*.}"
REPORT_FILE="${TODO_DIR}/report.${TODO_FILE##*.}"
SOMEDAY_FILE="${TODO_DIR}/someday.${TODO_FILE##*.}"
BACKLOG_File="${TODO_DIR}/backlog.${TODO_FILE##*.}"

# the now rule, replace it with keyword that you frequently query
TODO_NOW_RULE=${TODO_NOW_RULE:-"@|\+|#"}

# color
RED='\033[0;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
BLACK='\033[0;30m'
ORANGE='\033[0;33m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LGRAY='\033[0;37m'
DGRAY='\033[1;30m'
LRED='\033[1;31m'
LGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LBLUE='\033[1;34m'
LPURPLE='\033[1;35m'
LCYAN='\033[1;36m'
WHITE='\033[1;37m'
NO_C='\033[0m'

# set color for each priority
declare -A PRIOR_C
PRIOR_C[A]="${RED}"
PRIOR_C[B]="${YELLOW}"
PRIOR_C[C]="${GREEN}"
# PRIOR_C[D]="${LBLUE}"
# PRIOR_C[E]="${PURPLE}"
# PRIOR_C[F]=""
# PRIOR_C[G]=""
# PRIOR_C[H]=""
# PRIOR_C[I]=""
# PRIOR_C[J]=""
# PRIOR_C[K]=""
# PRIOR_C[L]=""
# PRIOR_C[M]=""
# PRIOR_C[N]=""
# PRIOR_C[O]=""
# PRIOR_C[P]=""
# PRIOR_C[Q]=""
# PRIOR_C[R]=""
# PRIOR_C[S]=""
# PRIOR_C[T]=""
# PRIOR_C[U]=""
# PRIOR_C[V]=""
# PRIOR_C[W]=""
# PRIOR_C[X]=""
# PRIOR_C[Y]=""
# PRIOR_C=""
NO_PRIOR_C="${NO_C}"
DONE_C="${DGRAY}"

# initial flag
text=""
will_list=0
verbose=false
list_files=()
list_files+=("${TODO_FILE}")
grep_word_rule='.*'

# perform various checking
check_dir_usuable "${TODO_DIR}"

check_file_usuable "${DONE_FILE}"
check_file_usuable "${TODO_FILE}"
check_file_usuable "${REPORT_FILE}"
check_file_usuable "${SOMEDAY_FILE}"
check_file_usuable "${BACKLOG_File}"


# if no arg, list todo
if [ $# -eq 0 ]; then 
    will_list=1
fi

# too lazy to do checking
while [[ $# -gt 0 ]]; do
    case $1 in 
        -n|--now)
            action='filter'
            will_list=1
            grep_word_rule="${TODO_NOW_RULE}"
            shift
            ;;
        -app|--append)
            action='append'
            target_index=$2
            text="$3"
            shift
            shift
            shift
            ;;
        -l|--list)
            will_list=1
            list_files+=( "${DONE_FILE}" )
            if [ -f ${TODO_DIR}/$2.${TODO_FILE##*.} ]; then
                list_files=(${TODO_DIR}/$2.${TODO_FILE##*.})
                shift
            fi
            shift
            ;;
        -a|--add)
            action='add'
            text="$2"
            shift
            shift
            ;;
        -v|--verbose)
            verbose=true
            shift
            ;;
        -t|--target)
            if [ -f ${TODO_DIR}/$2.${TODO_FILE##*.} ]; then
                target_file="${TODO_DIR}/$2.${TODO_FILE##*.}"
                shift
            fi
            shift
            ;;
        -f|--filter)
            action='filter'
            will_list=1
            grep_word_rule=$2
            shift
            shift
            ;;
        -h|--help)
            print_help
            exit 0
            ;;
        -o|--open)
            cd ${TODO_DIR} || exit
            [ -z $2 ] && ${EDITOR} ${TODO_FILE} && exit 0 # open todo by default
            ${EDITOR} $2.${TODO_FILE##*.} && exit 0 # otherwise open the choice
            ;;
        -c|--clean) # clean
            action='archive'
            break
            ;;
        -r|--report)
            action='report'
            break
            ;;
        -p|--prior)
            action='priority'
            target_index=$2
            [ -n $3 ] && add_prior_level=$(echo $3 | tr '[:lower:]' '[:upper:]')
            break
            ;;
        -d|--done)
            action='done'
            target_index=$2
            break
            ;;
        -del|--delete)
            action='remove'
            target_index="$2"
            break
            ;;
        -mov|--move)
            action='move'
            target_index="$2"
            [ ! -f ${TODO_DIR}/$3.${TODO_FILE##*.} ] && exit 1 
            desti_target_file="${TODO_DIR}/$3.${TODO_FILE##*.}"
            break 
            ;;
        *) # catch all
            action='add'
            text="$*"
            break
            ;;
    esac
done

today="$(date +%Y-%m-%d)"
target_file=${target_file:-${TODO_FILE}} # default target_file is ${TODO_FILE}

# translate value of $target_index
# 'i..j' to (i i+1 i+2 ... j-2 j-1 j) and sort it too
# ex. (1,3..8,4) -> (1,3,4,5,6,7,8)
if [ -z "${target_index##*[!0-9]*}" ]; then # check if it isn't normal integer
    target_indices_raw="${target_index}"
    target_indices=(${target_indices_raw//,/ })
    for index in ${target_indices[@]}; do
        if [[ ${index} =~ ^[0-9]+..[0-9]+$ ]]; then # find i..j pattern
            match=${BASH_REMATCH[0]}
            start_i=$(echo ${match} | cut -d '.' -f 1)
            end_i=$(echo ${match} | cut -d '.' -f 3)
            for ((i="${start_i}"; i<="${end_i}"; i++)); do # extract index
                target_indices=( ${target_indices[@]} $i)
            done
        fi
    done
    target_indices=( "${target_indices[@]}" "${to_be_add_index}")
    target_indices=("${target_indices[@]/[0-9]*..[0-9]*/}")
    IFS=$'\n' target_indices=($(sort -u -V <<<"${target_indices[*]}")); unset IFS
else
    target_indices=($target_index)
fi

# action that contain target_index are put in the loop
for target_index in ${target_indices[@]} ; do
    target_index=$((${target_index} - ${offset:-0}))
    case $action in
        append)
            sed -i.bak "${target_index}s/$/ ${text}/" ${target_file}
            ;;
        done)
            sed -i "${target_index}s/^([a-zA-Z]) //" ${target_file}
            sed -i.bak "${target_index}s/^/x ${today} /" ${target_file}
            ;;
        priority)
            sed -i "${target_index}s/^([a-zA-Z]) //" ${target_file} # delete old prior
            [ -n "${add_prior_level}" ] && sed -i.bak "${target_index}s/^/\(${add_prior_level}\) /" ${target_file} # add new prior
            ;;
        remove)
            sed -i.bak "${target_index}d" ${target_file} 
            offset=$((${offset}+1))
            ;;
        move)
            target_index_text="$(sed -n "${target_index}p" ${target_file})"
            echo ${target_index_text} >> ${desti_target_file}
            offset=$((${offset}+1))
            ;;
    esac
done

# action that doesn't have target_index
case $action in
    add)
        cp ${target_file} ${target_file}.bak
        echo "${today} ${text}" >> "${target_file}"
        ;;
    report)
            not_done="$(grep -E '^[^x]' "${TODO_FILE}" | wc -l)"
        done="$(grep -E '^x' "${TODO_FILE}" | wc -l "${DONE_FILE}" | cut -d ' ' -f -1)"
        echo "$(date +%Y-%m-%dT%H:%M:%S) ${not_done} ${done}" >> "${REPORT_FILE}"
        ;;
    archive)
        sed -n "/^x /p" ${target_file} >> ${DONE_FILE}
        sed -i.bak "/^x /d" ${target_file}
        sort -o ${DONE_FILE}{,}
        ;;
esac

sort -o ${target_file}{,}

# list todo
if [ ${will_list} -eq 1 ]; then
    line_number=1
    for list_file in ${list_files[@]} ; do
        while IFS= read -r line; do
            color=${NO_PRIOR_C}
            prior_regex='\([a-zA-Z]\)'
            valid_date_regex="[0-9]{4}-(((0[13578]|(10|12))-(0[1-9]|[1-2][0-9]|3[0-1]))|(02-(0[1-9]|[1-2][0-9]))|((0[469]|11)-(0[1-9]|[1-2][0-9]|30)))"
            if [[ ${line} =~ ^$prior_regex ]]; then
                prior="${BASH_REMATCH[0]:1:1}"
                color=${PRIOR_C[$prior]}
            elif [[ ${line} =~ ^[xX] ]]; then
                color=${DONE_C}
            fi
            # filter first then print output with color by priority
            if [[ ${line} =~ ${grep_word_rule} ]]; then 
                echo -e "$line_number:${color}$line${NO_C}"
            fi
            line_number=$(( line_number + 1 ))
        done < ${list_file}
    done
fi
